spring:
  datasource:
    url: _JDBC_URL_
    username: _DB_USER_
    password: _DB_PASSWORD_
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create