spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/modu
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    show-sql: true
logging:
  level:
    com.flab.modu: debug
    org.springframework.jdbc: DEBUG
